[package]
name = "fractal-generator"
version = "0.1.0"
authors = ["mthom26 <mthom2626@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.1"
num-complex = "0.2.1"
clap = "2.33.0"
indicatif = "0.11.0"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
